version: '3.7'

volumes:
    node_modules:
 
services:
    backend:
        build:
            dockerfile: dockerfile
            context: ./
        user: '${UID:-1000}:${GID:-1000}'
        volumes:
            - node_modules:/app/node_modules
        env_file: .env
        ports:
            - '3001:3001'
        command: npm run start
